spring.application.name=portal

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/portal_sekolah
spring.datasource.username=postgres
spring.datasource.password=openpgpwd

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (opsional)
server.port=8080

# Actuator endpoints (opsional)
management.endpoints.web.exposure.include=health,info


upload.dir=uploads/foto

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.portal=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=herysuherynoreply@gmail.com
spring.mail.password=frys gryd gsqq tesd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true